services:
  garcisslink:
    image: garciss/garcisslink:latest
    container_name: garcisslink
    restart: always
    environment:
      - ConnectionStrings__RedisConnection
    ports:
      - "7325:80"
      - "7326:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost/health | grep -w '[Hh]ealthy' || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 2s
